site_name: Whole_pipelines
pages:
    - Home: index.md
    - User Guide:
        - 'Setting': 'user-guide/setting.md'
        - 'Main pipelines': 'user-guide/main pipelines.md'
        - 'After main pipelines': 'user-guide/aft main pipelines.md'
        - 'Output file': 'user-guide/output file.md'
        - 'Special Need': 'user-guide/special need.md'
    - API: api.md
    - TODO: todo.md

theme: readthedocs
